MID-6856: Add support for ignore-missing flag in S3 actions

diff --git a/s3/download/action.yaml b/s3/download/action.yaml
--- a/s3/download/action.yaml
+++ b/s3/download/action.yaml
@@ -22,6 +22,10 @@ inputs:
     required: false
     description: AWS Region
     default: eu-central-1
+  ignore-missing:
+    required: false
+    description: Do not fail if no objects are found at the source path.
+    default: 'false'
   aws-http-proxy:
     required: false
     description: URI for aws-cli HTTP proxy
@@ -46,4 +50,12 @@ runs:
         AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
         HTTP_PROXY: ${{ inputs.aws-http-proxy }}
         HTTPS_PROXY: ${{ inputs.aws-https-proxy }}
-      run: s5cmd --log error cp "s3://${{ inputs.aws-bucket }}/${{ inputs.src-path }}*" "${{ github.workspace }}/${{ inputs.dst-path }}"
+      run: |
+        if ! s5cmd --log error cp "s3://${{ inputs.aws-bucket }}/${{ inputs.src-path }}*" "${{ github.workspace }}/${{ inputs.dst-path }}"; then
+          if [ "${{ inputs.ignore-missing }}" = "true" ]; then
+            echo "No objects found at s3://${{ inputs.aws-bucket }}/${{ inputs.src-path }} (ignored)"
+          else
+            echo "::error::No objects found at s3://${{ inputs.aws-bucket }}/${{ inputs.src-path }}"
+            exit 1
+          fi
+        fi
